apiVersion: v2
name: cloudflare-dyndns
description: Cloudflare DynDNS middleware for AVM FRITZ!Box and other DynDNS clients
type: application
version: 0.1.0
appVersion: "0.0.0"
kubeVersion: ">=1.23.0-0"
home: https://github.com/l480/cloudflare-dyndns
sources:
  - https://github.com/l480/cloudflare-dyndns
keywords:
  - dyndns
  - dynamic-dns
  - cloudflare
  - dns
  - fritzbox
maintainers:
  - name: Nico Struck
    email: mail@nico-struck.de
    url: https://github.com/l480
