name: Build and push Docker images to GitHub Packages
on: push
jobs:
  cloudflare_dyndns_docker-build-push:
    name: Build and push cloudflare-dyndns docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Lowercase repository owner
        run: |
          echo "REPO_OWNER=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}
      - name: Build and push image to GitHub Packages
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          context: ./
          push: true
          platforms: linux/amd64,linux/arm/v6,linux/arm64/v8
          tags: ghcr.io/${{ env.REPO_OWNER }}/cloudflare-dyndns:latest
